import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import {auth} from '@/auth'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session =  await auth()

  console.log(session)
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body style={{backgroundColor: "#1a1f29", color: "#ccd2da"}} className={inter.className}>{children}</body>
    </html>
    </SessionProvider>
  );
}
